import { GLOSSARY, lookupGlossary, type GlossaryEntry } from "./glossary";

export * from "./gujarati";
export * from "./doctypes";
export { DISCLAIMER, GLOSSARY, lookupGlossary, glossarySize, mergeCustomTerms, STATUTE_TOKENS } from "./glossary";
export type { GlossaryEntry, LegalCategory, CustomTerm } from "./glossary";
export { STATUTE_MAP, COURT_ABBREVIATIONS, lookupStatute } from "./statute-map";
export type { StatuteMapping } from "./statute-map";
export { detectDocType, preflightDocument } from "./classify";
export type { TypeDetection, DocumentPreflight } from "./classify";

/** Shared vocabulary types for the pipeline stages. */

export type BlockKind =
  | "document_title"
  | "heading_1"
  | "heading_2"
  | "heading_3"
  | "court_name"
  | "case_number"
  | "party_block"
  | "body"
  | "numbered_para"
  | "list_item"
  | "clause"
  | "sub_clause"
  | "table_header"
  | "table_cell"
  | "citation"
  | "quotation"
  | "signature_block"
  | "seal_note"
  | "footer"
  | "header"
  | "page_break";

export type TranslationState =
  | "pending"
  | "ai"
  | "ai_flagged"
  | "human_accepted"
  | "human_edited"
  | "rejected"
  | "failed";

export interface Block {
  id: string;
  ordinal: number;
  pageNumber: number;
  kind: BlockKind;
  sourceText: string;
  targetText: string;
  translationState: TranslationState;
  tokenCount: number;
  charStart?: number;
  charEnd?: number;
  meta: BlockMeta;
  confidence?: number;
}

export interface BlockMeta {
  /** Visual hint used for structure detection. */
  fontSize?: number;
  isBold?: boolean;
  indent?: number;
  /** Detected clause label, e.g. "12." or "12.1" — treated as non-translatable. */
  clauseLabel?: string;
  /** Nesting depth for numbered clauses. */
  clauseDepth?: number;
  tableId?: string;
  tableRow?: number;
  tableCol?: number;
  isTableHeader?: boolean;
  /** Glossary term IDs that appear in this block's source. */
  glossaryHits?: string[];
  /** Short preceding context used to keep party names consistent across chunks. */
  isContinuation?: boolean;
  /** Block came from OCR (lower trust) vs an embedded text layer. */
  fromOcr?: boolean;
  pageConfidence?: number;
  /**
   * Block was generated by our own heuristics rather than read from the file.
   *
   * `attachFooterDetection` injects a standalone page-number line when a page
   * labels itself in running text. That line is not a source sentence, so it is
   * marked synthetic and excluded from translation and datum extraction —
   * otherwise every page would contribute a spurious "page 4" numeral.
   */
  synthetic?: boolean;
}

export type DatumKind =
  | "number"
  | "currency"
  | "date"
  | "time"
  | "percentage"
  | "section_ref"
  | "case_number"
  | "statute"
  | "person_name"
  | "party_name"
  | "place"
  | "address_pin"
  | "count_phrase"
  | "ordinal";

export type DatumStatus =
  | "matched"
  | "changed"
  | "missing"
  | "added"
  | "ambiguous"
  | "unchecked";

export interface Datum {
  id: string;
  kind: DatumKind;
  /** Exactly as written in the source. */
  surface: string;
  /** Canonical comparable value (see `verify/datum.ts`). */
  normalized: string;
  /** Surrounding text for human context. */
  context: string;
  blockId?: string;
  targetBlockId?: string;
  pageNumber?: number;
  /** Matched/attempted English surface. */
  targetSurface?: string;
  status: DatumStatus;
  severity: "critical" | "major" | "minor";
  /** Extra kind-specific fields (e.g. act short-form, currency code). */
  meta?: Record<string, string | number | boolean>;
}

export type Severity = "critical" | "major" | "minor" | "info";

export interface Finding {
  id: string;
  /** Machine-readable check code, e.g. `datum.changed`. */
  check: string;
  category: string;
  severity: Severity;
  blockId?: string;
  datumId?: string;
  pageNumber?: number;
  title: string;
  detail: string;
  suggestion: string;
  sourceExcerpt: string;
  targetExcerpt: string;
  status: "open" | "accepted" | "resolved" | "dismissed";
}

export interface GlossaryHit {
  entry: GlossaryEntry;
  surface: string;
  start: number;
  end: number;
}

export { lookupGlossary as lookupTerm };